### ISSUE TITLE
Testing of the issues with the label "clarification needed"

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2079]
This issue is a gitcoin bounty. 

#### ToDo:
- [ ] Testing of the issues with the label "clarifaction needed"
- [ ] Describe when this issue occurs
- [ ] Tag me (@nivida) 
- [ ] Reference the issue here

#### Description template: 
```
Expected behavior:

Actual behavior:

Steps to reproduce the behavior:

1. [First step]
2. [Second step]
3. [and so on...]

Error Logs:

Versions:
[NPM, Node, Web3.js, OS, device...]
```

**Comment by dev1644** [comment]
#918
#998

**Comment by dev1644** [comment]
#918
