### ISSUE TITLE
Answering issues with the label "support"

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2080]
This is a gitcoin bounty.

#### ToDo:
- [ ] Answer the question
- [ ] Tag @nivida if you couldn't find a solution and describe it.
- [ ] Tag @nivida if the documentation is wrong and add a URL to the docs and describe what's wrong.
- [ ] Tag @nivida if the documentation should be improved and describe how.
- [ ] Reference the issue here.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 700.0 DAI (700.0 USD @ $1.0/DAI)  attached to it as part of the Ethereum Foundation fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2080/1940).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ethereum/web3.js/2080/1940).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $43,446.17 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 10 months, 2 weeks ago.
Please review their action plans below:


**1) [joshstevens19](https://gitcoin.co/joshstevens19) has started work.**

Hey, i work with web3 on a daily basis, i am doing PRs to it all the time and i speak to Sam a lot over telegram so i feel i could be really beneficial to this. I am already helping people on the PR and issues, so me helping support issues would not be a problem.  

Thanks
Josh
**2) [ra9](https://gitcoin.co/ra9) has started work.**

Hey I am Carlos from Liberia, I love helping out with question and issues , so helping out will not be a problem for me.
**3) [huanzhang89](https://gitcoin.co/huanzhang89) has started work.**

Have already started work answer support issues on github as agreed with Sam
**4) [dragonsinmeliodas](https://gitcoin.co/dragonsinmeliodas) has started work.**

Hi helping out on the issues is not much of a problem , i will try to provide crisp and original resolutions to the issues
**5) [vikaskyadav](https://gitcoin.co/vikaskyadav) has started work.**

I have already answered some issues earlier. won't be a problem.
**6) [dev1644](https://gitcoin.co/dev1644) has started work.**

Hi, I am a Developer experience in Solidity, Full-Stack JavaScript (ReactJs & NodeJs). I have a good understanding of Ethereum Network and Geth, want to help web3js Community to clean up issues.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2080/1940).

**Comment by ctrlaltvikas** [comment]
Hi ,@nivida. I've already started answering the issues labelled with `suppport`. I can't start work officially on gitcoin because of some issue with my gitcoin account(which is under processing). Will that be ok?

Issues:

- https://github.com/ethereum/web3.js/issues/1781

- https://github.com/ethereum/web3.js/issues/2029

- https://github.com/ethereum/web3.js/issues/2029

- https://github.com/ethereum/web3.js/issues/1896

**Comment by spm32** [comment]
Hey @vikaskyadav looks like you've been approved from my side so we'll be able to pay you out for the issues you answer :)

**Comment by joshstevens19** [comment]
will just post my support answers in here as i go https://github.com/ethereum/web3.js/issues/2108

**Comment by joshstevens19** [comment]
https://github.com/ethereum/web3.js/issues/2117

**Comment by joshstevens19** [comment]
https://github.com/ethereum/web3.js/issues/2104

**Comment by nemani** [comment]
Will post my links to answers in this thread as I comment! :smile: 
https://github.com/ethereum/web3.js/issues/1211#issuecomment-447495366

https://github.com/ethereum/web3.js/issues/1409#issuecomment-447496563

**Comment by Huanzhang89** [comment]
https://github.com/ethereum/web3.js/issues/1781#issuecomment-443816896

**Comment by Huanzhang89** [comment]
https://github.com/ethereum/web3.js/issues/2069

**Comment by Huanzhang89** [comment]
https://github.com/ethereum/web3.js/issues/2072

**Comment by Huanzhang89** [comment]
https://github.com/ethereum/web3.js/issues/2059

**Comment by Huanzhang89** [comment]
https://github.com/ethereum/web3.js/issues/2035

**Comment by Huanzhang89** [comment]
https://github.com/ethereum/web3.js/issues/2002

**Comment by Huanzhang89** [comment]
https://github.com/ethereum/web3.js/issues/1894

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 700.0 DAI (700.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@vikaskyadav](https://gitcoin.co/profile/vikaskyadav)
 2. [@dragonsinmeliodas](https://gitcoin.co/profile/dragonsinmeliodas)
 3. [@flash-git](https://gitcoin.co/profile/flash-git)
 4. [@chankruze](https://gitcoin.co/profile/chankruze)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/ethereum/web3.js/issues/2080#issuecomment-450754423) by @chankruze
* (Link Not Provided) by @Flash-Git
* (Link Not Provided) by @DragonSinMeliodas
* [PR](https://github.com/ethereum/web3.js/issues/2080#issuecomment-445467773) by @vikaskyadav

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2080/1940)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ethereum/web3.js/2080/1940).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $45,900.55 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by ctrlaltvikas** [comment]
I'll keep on adding more answers to the labels cuz I'm liking helping others this way too.

**Comment by sbansal96** [comment]
#1894

**Comment by Huanzhang89** [comment]
https://github.com/ethereum/web3.js/issues/2141

**Comment by Huanzhang89** [comment]
https://github.com/ethereum/web3.js/issues/2137

**Comment by sbansal96** [comment]
#1083

**Comment by Flash-Git** [comment]
[#1925](https://github.com/ethereum/web3.js/issues/1925)

**Comment by Flash-Git** [comment]
[#1918](https://github.com/ethereum/web3.js/issues/1918)

**Comment by Flash-Git** [comment]
[#1501](https://github.com/ethereum/web3.js/issues/1501)

**Comment by chankruze** [comment]
Hi ,@nivida. I answered some of the issues labelled with `suppport`.The issues i have answered are listed below.

**Issues Answered:**
- #2140 
- #2137 
- #1382 
- #1894 
- #1972 
- #1896 
- #1554

**Comment by Flash-Git** [comment]
[#2156](https://github.com/ethereum/web3.js/issues/2156)

**Comment by Flash-Git** [comment]
[#2154](https://github.com/ethereum/web3.js/issues/2154)

**Comment by Flash-Git** [comment]
[#2155](https://github.com/ethereum/web3.js/issues/2155)

**Comment by Flash-Git** [comment]
[#2161](https://github.com/ethereum/web3.js/issues/2161)

**Comment by Flash-Git** [comment]
[#2160](https://github.com/ethereum/web3.js/issues/2160)

**Comment by Flash-Git** [comment]
[#2163](https://github.com/ethereum/web3.js/issues/2163)

**Comment by dev1644** [comment]
Hi @nivida, I have answered to the following issues, some of the issues don't have `support` label, so as per my understanding of the issue and the help required, I referenced some of them here. 

**Issue Answered**

- #1108
- #1584
- #1884 
- #2019
- #2157
- #2167
- #2169 
- #2170
- #2173
- #2175
- #2193
- #2212
- #2210

**Comment by rushi7997** [comment]
HI @nivida i am gettiong this error when i am trying to install web3@1.0.0-beta.26 please help



```

npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall C:\Users\ramir\AppData\Roaming\npm\node_modules\web3\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install C:\Users\ramir\AppData\Roaming\npm\node_modules\web3\node_modules\scrypt
> node-gyp rebuild


C:\Users\ramir\AppData\Roaming\npm\node_modules\web3\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\ramir\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\ramir\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
C:\Users\ramir\AppData\Roaming\npm\node_modules\web3\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\ramir\AppData\Roaming\npm\node_modules\web3\node_modules\scrypt\build\copied_files.vcxproj(20,3): error MSB4019: The importe
d project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the
file exists on disk.
C:\Users\ramir\AppData\Roaming\npm\node_modules\web3\node_modules\scrypt\build\scrypt_wrapper.vcxproj(20,3): error MSB4019: The impor
ted project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that th
e file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ramir\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ramir\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ramir\AppData\Roaming\npm\node_modules\web3\node_modules\scrypt
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ramir\AppData\Roaming\npm-cache\_logs\2019-01-21T06_10_57_894Z-debug.log
```

**Comment by nivida** [comment]
@dev1644 I think this is okay and @ceresstation will see this. :)

**Comment by ctrlaltvikas** [comment]
hey @nivida  when will you process the bounty payment?

**Comment by nivida** [comment]
@vikaskyadav Gitcoin (@ceresstation) told me they will pay out all the bounties.

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 56.00000  DAI (56.0 USD @ $1.0/DAI) has been granted to @vikaskyadav for this issue from @ceresstation. ⚡️ 

Nice work @vikaskyadav! Your tip has automatically been deposited in the ETH address we have on file.

 * $53486.27 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__This Bounty has been completed.__

Additional Tips for this Bounty:
* ceresstation tipped 56.0000 DAI worth 56.0 USD to vikaskyadav.

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2080/1940)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $52,786.27 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by chankruze** [comment]
Lol we get nothing !
Now i feel  have done nothing wrong quiting gitcoin !

**Comment by Huanzhang89** [comment]
@chankruze I'm inclined to agree with you but for a different reason.

Gitcoin just seems super slow and complex as well as hard to keep track of who actually did what. 

It also doesn't help that the person managing the gitcoin bounties from the EF is different from the maintainer who actively reads the issues list of web3. 

Another problem with using gitcoin for bounties like this one is that its difficult to decide how to split the bounty amongst all the people that chip in on one issue or more while also duplicating answers and replying with the same thing as the person before them.

The end result though, is inevitably that people who can actually help get frustrated with these issues and stop contributing. The money is like a drop in the ocean for most people who have the skills to resolve these issues but including a small bounty like this attracts a lot of people who just want the money and thus creating a lot spam too.

The system definitely needs to change...

**Comment by spm32** [comment]
@chankruze @Huanzhang89 Sorry, just wanted to note that everyone who completed work will get paid, we just had a small issue with advanced payout that we're fixing shortly. After that I'll be able to pay everyone out properly.

@Huanzhang89 I do agree with you on your other points though, we definitely need to smooth out the process for determining who did what work on these kinds of cooperative bounties and need to make sure it's set up in a way that encourages people to get more involved in repos they like. To avoid crowding the thread let's chat more on the community slack about what some of the short term / long term fixes look like (I'm notscottmoore).

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 42.00000  DAI (42.0 USD @ $1.0/DAI) has been granted to @joshstevens19 for this issue from @ceresstation. ⚡️ 

Nice work @joshstevens19! Your tip has automatically been deposited in the ETH address we have on file.

 * $74217.66 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 35.00000  DAI (35.0 USD @ $1.0/DAI) has been granted to @nemaniarjun for this issue from @ceresstation. ⚡️ 

Nice work @nemaniarjun! Your tip has automatically been deposited in the ETH address we have on file.

 * $71810.03 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 238.00000  DAI (238.0 USD @ $1.0/DAI) has been granted to @dev1644 for this issue from @ceresstation. ⚡️ 

Nice work @dev1644! Your tip has automatically been deposited in the ETH address we have on file.

 * $71810.03 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 161.00000  DAI (161.0 USD @ $1.0/DAI) has been granted to @huanzhang89 for this issue from @ceresstation. ⚡️ 

Nice work @huanzhang89! To redeem your tip, login to Gitcoin at https://gitcoin.co/explorer and select 'Claim Tip' from dropdown menu in the top right, or check your email for a link to the tip redemption page. 

 * $71810.03 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 35.00000  DAI (35.0 USD @ $1.0/DAI) has been granted to @dragonsinmeliodas for this issue from @ceresstation. ⚡️ 

Nice work @dragonsinmeliodas! To redeem your tip, login to Gitcoin at https://gitcoin.co/explorer and select 'Claim Tip' from dropdown menu in the top right, or check your email for a link to the tip redemption page. 

 * $71810.03 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 161.00000  DAI (161.0 USD @ $1.0/DAI) has been granted to @flash-git for this issue from @ceresstation. ⚡️ 

Nice work @flash-git! Your tip has automatically been deposited in the ETH address we have on file.

 * $71810.03 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 126.00000  DAI (126.0 USD @ $1.0/DAI) has been granted to @chankruze for this issue from @ceresstation. ⚡️ 

Nice work @chankruze! Your tip has automatically been deposited in the ETH address we have on file.

 * $71810.03 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by nogo10** [comment]
Is issue #2059 resolved, I get that error with version 1.2.x

**Comment by nogo10** [comment]
This error message: similar to issue #2059
```TypeError: Cannot read property 'slice' of undefined```
webpack-internal:///./node_modules/readable-stream/lib/_stream_writable.js:57 Uncaught

**Comment by nogo10** [comment]
?
