### ISSUE TITLE
Solving of the issues with the label "documentation"

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2081]
This is a gitcoin bounty.

#### ToDo:
- [ ] Fix the documentation.
- [ ] Create a PR with the fix and format the title like this: ```[documentation] Typo```
- [ ] Reference the issue in the PR and here.
- [ ] Be sure you tested it if the change describes another behavior.

**Comment by arku** [comment]
I've fixed #1924 in #2088

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 250.0 DAI (250.0 USD @ $1.0/DAI)  attached to it as part of the Ethereum Foundation fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2081/1939).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ethereum/web3.js/2081/1939).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $42,746.17 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by xiaods** [comment]
@nivida you mean fix all issue with label Documents? @arku is working on it?

**Comment by nivida** [comment]
@xiaods Exactly, that's what I mean. It should be possible to have multiple contributors working on this bounty. Gitcoin will pay out for each PR the correct amount.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 11 months, 4 weeks ago.
Please review their action plans below:


**1) [aj07](https://gitcoin.co/aj07) has started work.**

I would like to work on this. Probably, will submit multiple PR :)
**2) [flash-git](https://gitcoin.co/flash-git) has started work.**

I'm happy to go through the issues with the documentation label and fix what I'm able to. Does this work retroactively? I've fixed minor typos in the past.
**3) [michaelgee](https://gitcoin.co/michaelgee) has started work.**

I will correct the bugs and errors in the document  as required and make a pull request when done.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2081/1939).

**Comment by tcrowe** [comment]
✅Fixes confusion about `getAccounts`, `newAccount`, and `accounts.create()` https://github.com/ethereum/web3.js/pull/2124

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Work for 250.0 DAI (250.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@tcrowe](https://gitcoin.co/profile/tcrowe)
 2. [@flash-git](https://gitcoin.co/profile/flash-git)



@ceresstation please take a look at the submitted work:
* (Link Not Provided) by @Flash-Git
* [PR](https://github.com/ethereum/web3.js/pull/21242) by @tcrowe

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2081/1939)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ethereum/web3.js/2081/1939).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $48,587.52 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by tcrowe** [comment]
✅https://github.com/ethereum/web3.js/pull/2129 `web3.eth.accounts.privateKeyToAccount` hex string clarified

---

I never tried a cooperative bounty so I don't know if you're supposed to "Submit Work" once or multiple times. Chris Kuhn says it can only be done once. 🤷‍♂️

**Comment by spm32** [comment]
Hey @tcrowe just keep track of how many labelled issues you worked on and I'll pay you out for each one :)

**Comment by Flash-Git** [comment]
[#1814](https://github.com/ethereum/web3.js/pull/1814) and [#1790](https://github.com/ethereum/web3.js/pull/1790)

**Comment by nanspro** [comment]
I've fixed 

- https://github.com/ethereum/web3.js/issues/1874 in https://github.com/ethereum/web3.js/pull/2145

- https://github.com/ethereum/web3.js/issues/1440 in https://github.com/ethereum/web3.js/pull/2147

- https://github.com/ethereum/web3.js/issues/1686 in https://github.com/ethereum/web3.js/pull/2146

**Comment by Flash-Git** [comment]
[#2164](https://github.com/ethereum/web3.js/issues/2164) Not a fix so might not apply

**Comment by Flash-Git** [comment]
[#1717](https://github.com/ethereum/web3.js/issues/1717)

**Comment by nanspro** [comment]
Also fixed #1287 in https://github.com/ethereum/web3.js/pull/2148

**Comment by nanspro** [comment]
Fixed #1716 in https://github.com/ethereum/web3.js/pull/2149

**Comment by nanspro** [comment]
@ceresstation this bounty is ongoing, right?
I have solved 5 issues in total, links to them i have provided above!!

Also should i start work on gitcoin, is it necessary for the bounty?

**Comment by justcharlz** [comment]
@nivida and @ceresstation is this bounty still on?

**Comment by nivida** [comment]
Yes, this bounty is still open. I will talk later to @ceresstation for clarifing how long this bounty will be open. @charlie4biz
