### ISSUE TITLE
Add TypeScript typings for all packages

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2085]
This is a gitcoin bounty.

#### ToDo:
- [x] Add type definitions for all modules
- [x] Add dtslint tests for all modules
- [x] Add typings to PR template check list 
- [x] See if there's a coverage tool for dtslint tests

**Comment by joshstevens19** [comment]
Already on this as we know (as I was the one who suggested this change). Will wait for bounty to be created but will carry on with the tasks 😃

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 600.0 DAI (600.0 USD @ $1.0/DAI)  attached to it as part of the Ethereum Foundation fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2085/1903).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ethereum/web3.js/2085/1903).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $36,426.37 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 2 months ago.
Please review their action plans below:


**1) [joshstevens19](https://gitcoin.co/profile/joshstevens19) has been approved to start work.**

Hey i was the one who initially thought of this issue and suggested it to Sam. 

I have already done 2 PR for 2 packages and think i would be the correct suited for this job!

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2085/1903).


**2) [huanzhang89](https://gitcoin.co/profile/huanzhang89) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ethereum/web3.js/2085/1903?mutate_worker_action=approve&worker=huanzhang89) | [reject worker](https://gitcoin.co/issue/ethereum/web3.js/2085/1903?mutate_worker_action=reject&worker=huanzhang89))_.**

Will be helping Josh on this. First time using gitcoin, just trying this out :)

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2085/1903).


**3) [samthomson](https://gitcoin.co/profile/samthomson) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ethereum/web3.js/2085/1903?mutate_worker_action=approve&worker=samthomson) | [reject worker](https://gitcoin.co/issue/ethereum/web3.js/2085/1903?mutate_worker_action=reject&worker=samthomson))_.**

I have experience working with TypeScript including projects which moved from JS to Typescript. Would be happy to help out with this.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2085/1903).

**Comment by spm32** [comment]
Just approved you @joshstevens19 glad to have you helping out :)

**Comment by joshstevens19** [comment]
Cheers Scott 👍

**Comment by gitcoinbot** [comment]
@joshstevens19 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2085/1903?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2085/1903?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2085/1903?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2085/1903?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2085/1903?snooze=100)

**Comment by joshstevens19** [comment]
Yes I have already done 3 PRs which have been merged for 3 packages, will be doing the other ones when I get a second! 😁

**Comment by joshstevens19** [comment]
PR number 1 - https://github.com/ethereum/web3.js/pull/2073

**Comment by joshstevens19** [comment]
PR number 2 - https://github.com/ethereum/web3.js/pull/2084

**Comment by joshstevens19** [comment]
PR number 3 - https://github.com/ethereum/web3.js/pull/2090

**Comment by joshstevens19** [comment]
PR number 4 - https://github.com/ethereum/web3.js/pull/2112

**Comment by joshstevens19** [comment]
PR number 5 - https://github.com/ethereum/web3.js/pull/2096

**Comment by joshstevens19** [comment]
PR number 6 - https://github.com/ethereum/web3.js/pull/2114

**Comment by joshstevens19** [comment]
PR number 7 - https://github.com/ethereum/web3.js/pull/2118

**Comment by joshstevens19** [comment]
PR number 8 - https://github.com/ethereum/web3.js/pull/2119

**Comment by joshstevens19** [comment]
PR number 9 - https://github.com/ethereum/web3.js/pull/2121

**Comment by joshstevens19** [comment]
PR number 10 - https://github.com/ethereum/web3.js/pull/2122

**Comment by joshstevens19** [comment]
PR number 11 - https://github.com/ethereum/web3.js/pull/2123

**Comment by joshstevens19** [comment]
PR number 12 - https://github.com/ethereum/web3.js/pull/2125

**Comment by joshstevens19** [comment]
PR number 13 - https://github.com/ethereum/web3.js/pull/2128

**Comment by joshstevens19** [comment]
PR number 14 - https://github.com/ethereum/web3.js/pull/2130

**Comment by joshstevens19** [comment]
Final PR https://github.com/ethereum/web3.js/pull/2133

**Comment by nivida** [comment]
@ceresstation This bounty is now done :) 
Thanks to @joshstevens19 for this awesome work!

**Comment by joshstevens19** [comment]
@ceresstation I have submitted the work on gitcoin 👍

**Comment by joshstevens19** [comment]
https://gitcoin.co/issue/ethereum/web3.js/2085/1903

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 600.0 DAI (600.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@joshstevens19](https://gitcoin.co/profile/joshstevens19)



@ceresstation please take a look at the submitted work:
* [PR](They are all on the main bounty ticket - https://github.com/ethereum/web3.js/issues/2085) by @joshstevens19

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2085/1903)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ethereum/web3.js/2085/1903).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $46,522.24 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by joshstevens19** [comment]
@ceresstation hey when will the gitcoin bounty be paid out ?

**Comment by spm32** [comment]
Hey @joshstevens19 sorry for the delay here, paying you out now :)

**Comment by gitcoinbot** [comment]
<table>
<tr>
<td>
<a title='Javascript Master Scriber' href='https://gitcoin.co/kudos/54/javascript_master_scriber'> <img width='250' src='https://gitcoin.co/dynamic/kudos/54/javascript_master_scriber' alt='Javascript Master Scriber'> </a> 
</td>
<td>
⚡️ A *Javascript Master Scriber* Kudos has been sent to @joshstevens19 for this issue from @ceresstation. ⚡️ 

Nice work @joshstevens19! 
Your Kudos has automatically been sent in the ETH address we have on file.
</td>
</tr>
</table>

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 600.0 DAI (600.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @joshstevens19.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2085/1903)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $46,136.83 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
