### ISSUE TITLE
Create live examples for the documentation examples.

### ISSUE THREAD

**Issue by nivida** [ethereum/web3.js#2089]
## Documentation Feature Request:
Currently, many developers have trouble to understand how to interact with the ethereum blockchain over Web3.js/JSON-RPC. The documentation is not bad but if you just started to build a Dapp it's hard to do the first steps. 

That's why I would like to have live examples with JsFiddle.

#### ToDo's: 
- [ ] Check if ethereum-js really works otherwise have a look at eWASM.
- [ ] Create simple example on JsFiddle.
- [ ] Check if there is a nice way to provide these examples with readthedocs.
- [ ] This examples could be placed in a separate repository. 
        (tag me and I will create a repository and give you access)

##### Resources 
https://github.com/ethereumjs/browser-builds/tree/master/dist/ethereumjs-vm
https://docs.jsfiddle.net/github-integration/untitled-1

> Thanks Melonport for this idea ;-)

**Comment by nivida** [comment]
Note for me: This would be a nice bounty for Gitcoin 🤔

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 250.0 DAI (250.0 USD @ $1.0/DAI)  attached to it as part of the Ethereum Foundation fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2089/1938).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/ethereum/web3.js/2089/1938).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $42,496.17 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by anshumanv** [comment]
@nivida how about serving the already present [examples](https://github.com/ethereum/web3.js/tree/master/example) on a static page, can it help in any way? 🤔

**Comment by nivida** [comment]
@anshumanv Thanks for your idea but I would like to have interactive examples for the 1.0 documentation. The examples you mention are unfortunately written with 0.20. 
It would be great if the developer could play around with the API while reading the documentation. 😄

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 11 months ago.
Please review their action plans below:


**1) [flash-git](https://gitcoin.co/flash-git) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?mutate_worker_action=approve&worker=flash-git) | [reject worker](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?mutate_worker_action=reject&worker=flash-git))_.**

I would love to do this, I have experience with web3 and already have a few snippets that might be useful.
Unfortunately I can't tell whether it has been started yet, the repo linked is empty. If there is still a sizeable amount of work to be done, I'm happy to start immediately!
**2) [alexanmtz](https://gitcoin.co/alexanmtz) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?mutate_worker_action=approve&worker=alexanmtz) | [reject worker](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?mutate_worker_action=reject&worker=alexanmtz))_.**

I'm learning and I like to document while I'm doing. I created a Bounty platform as well: gitpay.me
**3) [juan21232](https://gitcoin.co/juan21232) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?mutate_worker_action=approve&worker=juan21232) | [reject worker](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?mutate_worker_action=reject&worker=juan21232))_.**

Quiero mi pago tengo desde 3 meses queno e cobrado digame sime vana pagar o no
**4) [theblockchaindeveloper](https://gitcoin.co/theblockchaindeveloper) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?mutate_worker_action=approve&worker=theblockchaindeveloper) | [reject worker](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?mutate_worker_action=reject&worker=theblockchaindeveloper))_.**

I will be appy to help. Thanks, Elad.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/ethereum/web3.js/2089/1938).

**Comment by Jorropo** [comment]
> (tag me and I will create a repository and give you access)

@nivida this is what I'm doing :wink:

**Comment by spm32** [comment]
Hey @nivida is it alright if we move forward with @Jorropo ?

**Comment by nivida** [comment]
@ceresstation Yes would be fine :) 

@Jorropo I'll talk to our DevOps guys that they create a repository for it. I'll add the information about the repository later here.

**Comment by msflorez** [comment]
Can we have a serie of examples like the Nextjs project https://github.com/zeit/next.js/tree/canary/examples ? I think that this would be a good way to see some examples already working, we can have `web3js-graphql`, `web3js-rest-api`, `web3js-nextjs`, `web3js-react`, `web3js-events`, among others, everything interacting with an API or a frontend, some more complex than others.

**Comment by nivida** [comment]
Yes, sure great idea! 
I should get the repository this week. We can then discuss further ideas in the issue list there. 

Thanks for your feedback. @fmauricios

**Comment by nivida** [comment]
@Jorropo 
This is the repository: 
https://github.com/ethereum/web3-examples

Feel free to create the structure you think it's the best for creating these examples. It would be cool if the structure would be open to having examples in vanilla JS, TypeScript and other superset languages.

**Comment by nivida** [comment]
@fmauricios If you would like to create the starter projects then please contact @Jorropo for coordinating with him. Btw. it will be possible to split up this bounty.

**Comment by Huanzhang89** [comment]
@Jorropo Hey, I would like to help with creating the live examples :) Recently did some work with Josh on creating the TS types for web3js so I think I have a good knowledge of how the library works.

**Comment by msflorez** [comment]
@Jorropo I would like to help too! We can plan some great examples.

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by Flash-Git** [comment]
I'm still happy to work on this. Have there been any updates?

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by dev1644** [comment]
I would also love to work on this, is @Jorropo still working on this?

**Comment by Huanzhang89** [comment]
Seems like the trail has gone a bit cold on this one. 
I’m happy to take the lead on this and get together with some of the others wanting to contribute on this and make a start?

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by nivida** [comment]
@ceresstation I think @Jorropo will not finish this bounty. But @Huanzhang89 would be interested to do it and he knows a friend that could help him out. 

I already started with some examples for v1.0.0-beta.38 specific things: 
https://github.com/ethereum/web3-examples

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by eswarasai** [comment]
@nivida -- I'd like to take this issue forward. I see that the example repo has already been created with a sample code. Next steps would be to make it work in JSFiddle and then add the code around using `web3.js` API right? Thanks!

cc: @ceresstation

**Comment by gitcoinbot** [comment]
@jorropo Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=1) | [3 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=3) | [5 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=5) | [10 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=10) | [100 days](https://gitcoin.co/issue/ethereum/web3.js/2089/1938?snooze=100)

**Comment by nivida** [comment]
@eswarasai Sorry for the late response. I've created a webpack example and a module example. Yes, we would have to create a documentation folder there and setting the things up for jsfiddle. I think @Huanzhang89 would also like to help :)

**Comment by eswarasai** [comment]
@nivida -- No problem. Thanks for the update. I'll get started on setting up JSFiddle and shall update you once done :)

@Huanzhang89 -- Would love to have your help on setting up docs and probably have clearer list of examples that are needed in various tech stacks. Thanks!

**Comment by eswarasai** [comment]
@nivida -- Does the examples need to be setup on JSFiddle or maybe you'd prefer [`Codesandbox.io`](https://codesandbox.io)?

It looks like it's pretty easy to import a GitHub repo and get started with it just by using the GitHub URL to the example directory. You can open the below URL in a browser and you can see that it automatically installs dependencies and sets up dev environment for you.

URL --> https://codesandbox.io/s/github/ethereum/web3-examples/tree/development/starters/webpack

Let me know your thoughts on taking this approach. That way, we can just focus on having multiple example directories with all sorts of combinations of libraries/frameworks that can be easily imported and played around with in Codesandbox. Also, I'd like to know if there's any communication channel that's available for the ease of having such discussions and deciding on things faster. Thanks!

**Comment by eswarasai** [comment]
@nivida -- Any update here?

**Comment by nivida** [comment]
@eswarasai Sorry for the late response. @OFRBG started to do some tests and created a PR in the [web3-examples](https://github.com/ethereum/web3-examples) repository. Feel free to join the two open discussions we have in the issue list there.

**Comment by Asone** [comment]
@nvidia : 

Some examples using non-node accounts ( v3 keystore decrypt, privatekeyToAccount, etc.) and showing different ways ( from most automated to least ) to deploy contracts & method call them would be great. 

I've found myself the way to do it but i'm not sure it is understable to everyone so that might be a great help to them. 

Also, docs sometime does not explicitly provide all the information a dev could gather for its own usage (e.g : all the options we can use on some methods) . It's quite understable as it might make doc too big, however, examples could fill the gap on this ?

**Comment by PSalant726** [comment]
I applied to start work on Gitcoin. Is [this issue](https://gitcoin.co/issue/ethereum/web3.js/2089/1938) still active?

**Comment by thecyberd3m0n** [comment]
Is this issue active? I see it opened in Gitcoin

**Comment by abuaesh** [comment]
Hello everyone,
What happened to this issue? 
I came across an article for @nivida and ended up here. Please let me know if there is something to be done here. Would like to help!
