### ISSUE TITLE
ENS Module improvements

### ISSUE THREAD

**Issue by cgewecke** [ethereum/web3.js#3225]
This is a tracking issue for improvements the ENS module - collecting various tickets for a push to improve.

- [x] Increase test coverage (esp. ResolverMethodHandler)
- [x] Increase code style consistency  
- [x] E2E tests
- [ ] Reduce impact on bundle size ( see #3179 )
- [x] Add option to use custom registry addresses ( #3010 )
- [ ] Support full registry API ( comments #2683 )
- [ ] Support reverse lookup ( #2683 )
- [ ] ENS name resolution wherever addresses are expected ( #540 )
- [x] Add ENS support for Goerli testnet (#3252)
- [ ] Improve the detection of the current network and the selection of the ENS registry
  + Since all deployed registries do have the same address can we remove the ``config.js`` file 
- [ ] Fix error handling for callbacks (UnhandledPromiseRejectionWarning)

**Comment by nivida** [comment]
Thanks for writing down the mentioned and additionally added points from you here on this issue!

 > ResolverMethodHandler

The ``ResolverMethodHandler`` does look extremely special but was back then the only solution we had to expose the same interface as we do know from the ``Contract`` object. I think it would be a check worth if there is a better cleaner way to achieve this. 

The first implementation of the ENS module from Nick: https://github.com/ethereum/web3.js/pull/886
Implements the missing functionalities: https://github.com/ethereum/web3.js/pull/1784
Finish after feedback from Fabian: https://github.com/ethereum/web3.js/pull/1855

> Reduce impact on bundle size  

Using function signatures from a simple list instead of having the entire ABI does probably already improve the bundle size a lot. This would remove the ``Contract`` dependency and we would use the ``Method`` object and ``eth_sendTransaction``/``eth_call`` method and the ABICoder directly. 

The used ``eth-ens-namehash`` dependency can probably not be replaced with another smaller simpler module (idk if there is an alternative solution).

I can't wait to have those capabilities implemented! 💪

**Comment by cgewecke** [comment]
Thanks @nivida, super helpful!

**Comment by nivida** [comment]
Btw.: @cgewecke I've started to implement the whole ENS Registry API and noticed that it isn't possible to pass custom ``eth_call`` options to any getter of the ENS module which can be a required feature.
