### ISSUE TITLE
Rewrite web3  and add .use functionality [aggregate]

### ISSUE THREAD

**Issue by frankiebee** [ethereum/web3.js#3848]
web3.js library needs to be modernized and easy to contribute to

### tasks:
- [ ] outline the arguments each package will receive on constructor
- [x] outline how provider reassignment works 
- [ ] rewrite packages to conform to outlines and be modern es6 ensure that their are test for individual packages
- [ ] introduce `.use` as outlined in living doc [here](https://hackmd.io/@esjFsrEDTMahtSwNs1zZHA/Sy-ULG44D)
- [ ] correct the type script

*ideally change tests as little as possible*

### packages that need to be rewritten:
- [ ] web3   
- [ ] web3-eth-abi              
- [ ] web3-eth2-core 
- [ ] web3-bzz [deprecate]
- [ ] web3-eth-accounts       
- [ ] web3-net 
- [x] web3-core    
- [ ] web3-eth-contract        
- [ ] web3-providers-http
- [x] web3-core-helpers        
- [ ] web3-eth-ens             
- [ ] web3-providers-ipc
- [ ] web3-core-method         
- [ ] web3-eth-iban            
- [ ] web3-providers-ws
- [ ] web3-core-promievent     
- [ ] web3-eth-personal        
- [ ] web3-shh [deprecate]
- [x] web3-core-requestmanager 
- [x] web3-utils
- [ ] web3-core-subscriptions  
- [ ] web3-eth                 

before rewriting packages:
- create or assign your self to a issue reflecting which package you are rewriting

when rewriting packages be sure to include:
- unit test that only tests the package
- inline documentation that can be interpreted by [documentation](https://www.npmjs.com/package/documentation) tool or jsdoc

when merged into base branch be sure to:
- check off package
- make sure the side issue for that package is closed

**please link all issues to here and check off packages after being rewritten**

**Comment by frankiebee** [comment]
the ongoing rewrite of core packages is in the branch `rewrite-core` see in draft PR #3944 

packages that need a request manager should inherit from web3-base

**Comment by frankiebee** [comment]
- Packages should keep their own unit tests in their own test directory
- have their own dependencies in the `package.json` file and their own `package-lock.json` file
- Packages should be written in type script and should pull common types like provider etc. from `web3-types`

**Comment by frankiebee** [comment]
The completion of this issue will require a major version bump when complete.
