### ISSUE TITLE
[Rewrite 4.x]  Web3 Core

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4311]
### Description  

Create package `web3-core` with some generic stuff which will be utilized to create other packages. 
 
### Related Issues / Feature Requests / Discussion

- [x] Create web3-core package structure for the 4.x #4426
- [x] Create `Web3Config` to encapsulate all the configuration options #4427
- [x] Create `Web3Context` class to hold all state objects #4428
- [x] Create `RequestManager` class to handle internal web3 requests #4429 
- [x] Create `SubscriptionManager` class to handle internal web3 requests #4430
- [x] Create `LocalStorageWallet` class to handle the wallet interaction #4431
- [x] Create `BatchRequest` class to handle JsonRpc batch feature #4432

### Acceptance Criteria 

- [x] README is added with overview and examples 
- [x] Required documentations are updated 
- [x] Test coverage is greater than 80% 

### External Libs
Follow Lib Selection checklist.
