### ISSUE TITLE
[Rewrite 4.x]  Http Provider

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4312]
### Description  

Create package `web3-providers-http` to server JSON RPC via HTTP

### Related Issues / Feature Requests / Discussion

- [x] #4371
    - [x] #4373 
    - [x] #4374 
- [x] #4379
- [x] #4380
- [x] #4381
- [x] #4456

### Acceptance Criteria

- [ ] README is added with overview and examples 
- [ ] Required documentations are updated 
- [ ] Test coverage is greater than 80% 
    - [ ] unit tests
    - [ ] integration tests
    - [ ] e2e tests
- [ ] Verify that no function left to be migrated

### Dependencies / Related Modules

- `web3-common` #4340

### Issues / Feature Requests to be considered
https://github.com/ChainSafe/web3.js/issues/3425 XMLHttpRequest errors handling
https://github.com/ChainSafe/web3.js/issues/4696

**Comment by spacesailor24** [comment]
This package needs to support:

- [ ] `request`
    - [ ] [ETH1 Style JSON RPC Schema](https://eth.wiki/json-rpc/API)
        - e.g.
            ```typescript
            {
                "jsonrpc": "2.0",
                "method": "some_rpcMethod",
                "params": [ ],
                "id": 67
            }
            ```
    - [ ] [ETH2 Style JSON RPC Schema](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v1#/Beacon)
        - e.g.
            - `GET` requests with URL parameters
                ```typescript
                `http://127.0.0.1/eth/v1/beacon/states/${state_id}/validators/${validator_id}`
                ```
            - `POST` requests with URL parameters and request body
                - e.g.
                    - [Publishing a signed block](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v1#/Beacon/publishBlock)
                    - [Submit attestation](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v1#/Beacon/submitPoolAttestations)
                    - [Submit attester slashing](https://ethereum.github.io/beacon-APIs/?urls.primaryName=v1#/Beacon/submitPoolAttestations)
