### ISSUE TITLE
[Rewrite 4.x] WebSocket Provider

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4313]
( This is Epic for 4.x Management ) 

### WebSocket Provider
Websocket Provider is used to send RPC calls over webSocket

### Related Issues / Feature Requests / Discussion

- [x] #4398
- [x] #4399
- [x] #4400
- [x] #4401
- [x] #4495
- [ ] Support of Basic Auth
- [ ] Fault Tolerant
- [ ] Implement all specs defined in core provider Interface

other issues:
> https://github.com/ChainSafe/web3.js/issues/4123
> https://github.com/ChainSafe/web3.js/issues/4162
> https://github.com/ChainSafe/web3.js/issues/4309

### Dependencies / Related Modules

- [ ]  #4340 Core Provider

### Documentation
- [ ] README ( overview, one code snippet example, .. )
- [ ] Websocket Provider documentation ( Integrated with CoreProvider, have an example snippet )

### External Libs
If need Inform TL and follow Lib Selection checklist.
