### ISSUE TITLE
[Rewrite 4.x] EIP1193 Provider

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4315]
### Description  

Create package `web3-providers-eip1193` to serve JSON RPC via [EIP-1193](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md)

### Related Issues / Feature Requests / Discussion

- [x] #4382
- Events:
    - [x] #4383
    - [x] #4384
    - [x] #4385
    - [x] #4386
    - [x] #4387
- [x] #4388

### Acceptance Criteria

- [ ] README is added with overview and examples 
- [ ] Required documentations are updated 
- [ ] Test coverage is greater than 80% 
    - [ ] unit tests
    - [ ] integration tests
    - [ ] e2e tests
- [ ] Verify that no function left to be migrated

### Dependencies / Related Modules

- `web3-common` #4340
- `web3-core` #4311
