### ISSUE TITLE
[Rewrite 4.x] ABI

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4316]
( This is Epic for 4.x Management ) 

### ABI
Functions for encoding and decoding parameters to ABI (Application Binary Interface)

### Features
- [ ] Encode function signature
- [ ] Encode event signature
- [ ] Encode / decode params
- [ ] Decode Logs 

### Dependencies / Related Modules
Utils

### Documentation
- [ ] README ( overview,  example, .. )
- [ ] Documentation
 
### Tests
Goal: >80% Coverage

- [ ] unit tests
- [ ] integration tests
- [ ] e2e tests

### Related Issues / Feature Requests / Discussion
https://github.com/ChainSafe/web3.js/issues/4590
https://github.com/ChainSafe/web3.js/issues/4591

### External Libs
Follow Lib Selection checklist.
