### ISSUE TITLE
[Rewrite 4.x] Eth

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4317]
( This is Epic for 4.x Management ) 

### Description

Create package `web3-eth` (using both [1.x](https://github.com/ChainSafe/web3.js/tree/1.x/packages/web3-eth) and [4.x-old](https://github.com/ChainSafe/web3.js/tree/4.x-old/packages/web3-eth) as inspiration)

### Related Issues / Feature Requests / Discussion

- [x] #4483
- [x] #4430
- [x] #4608
- [x] #4318
- [x] #4322
- [x] #4319
- [x] #4321
- [x] #4316
- [x] #4491
- [ ] Migrate errors as error constructors
- [ ] Address pending nonce [issue](https://github.com/ChainSafe/web3.js/issues/1741)

### Documentation
- [ ] README ( overview, example, .. )
- [ ] Eth functions documentation

### External Libs
