### ISSUE TITLE
[Rewrite 4.x] Contracts

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4318]
### Description  

Create package `web3-eth-contract` with for the ethereum contract interaction and management. 
 
### Related Issues / Feature Requests / Discussion

- [ ] Create web3-eth-contract package structure for the 4.x #4560
- [ ] Create Contract constructor with basic encoding/decoding methods #4561
- [ ] Implement static type interface for Contract #4562
- [ ] Implement Contract deployment interface #4563
- [ ] Implement Contract public interfaces #4564

### Acceptance Criteria 

- [x] README is added with overview and examples 
- [x] Required documentations are updated 
- [x] Test coverage is greater than 80% 

### Dependencies / Related Modules

[#web3-](https://github.com/ChainSafe/web3.js/issues/4317)

### External Libs
Follow Lib Selection checklist.
