### ISSUE TITLE
[Rewrite 4.x] Accounts / Wallet

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4319]
( This is Epic for 4.x Management ) 

### Accounts / Wallet
To generate, import Ethereum accounts and sign data and transactions.

### Features
- [x] https://github.com/ChainSafe/web3.js/issues/4472
- [x] https://github.com/ChainSafe/web3.js/issues/4473
- [x] https://github.com/ChainSafe/web3.js/issues/4474
- [x] https://github.com/ChainSafe/web3.js/issues/4475
- [x] https://github.com/ChainSafe/web3.js/issues/4476
- [x] https://github.com/ChainSafe/web3.js/issues/4477
- [ ] support BIP32 HD keys

### Other Tasks
- [ ] Internal Audit 

### Dependencies / Related Modules
dependent on: https://github.com/ChainSafe/web3.js/issues/4320

### Documentation
- [ ] README ( overview, example, .. )
- [ ] Documentation

### Related Issues / Feature Requests / Discussion
Security On the Wallet https://github.com/ChainSafe/web3.js/issues/2739

### External Libs
Follow Lib Selection checklist.
