### ISSUE TITLE
[Rewrite 4.x] Eth Transaction

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4320]
( This is Epic for 4.x Management ) 

### Transaction
Supports sending Transaction.
Validate Transaction.
Fill default values if requested by user.

### TODOs

- [x] #4651
- [x] #4652
- [x] Discuss technique to determine default transaction pricing (namely EIP-1559 properties)

#### Nice to Haves

- [ ] [accessListify](https://docs.ethers.io/v5/api/utils/transactions/#utils-accessListify)
- [ ] [parseTransaction](https://docs.ethers.io/v5/api/utils/transactions/#utils-parseTransaction)
    - [ ] This could be implemented as a standalone method, but creating a transaction object should support serialized transactions for instantiation
- [ ] [serializeTransaction](https://docs.ethers.io/v5/api/utils/transactions/#utils-parseTransaction)
    - This could probably be achieved by exposing a serialize method from `@ethereumjs/tx` object

### Dependencies / Related Modules
Providers
Web3 Eth
Wallet / Accounts

### Documentation
- [ ] README ( overview, example, .. )
- [ ] Documentation
 
### Tests
Goal: >80% Coverage

- [ ] unit tests
- [ ] integration tests
- [ ] e2e tests

### Related Issues / Feature Requests / Discussion
- [ ] https://github.com/ChainSafe/web3.js/issues/3608
- [ ] https://github.com/ChainSafe/web3.js/issues/4034
- [x] https://github.com/ChainSafe/web3.js/issues/4509
- [ ] https://github.com/ChainSafe/web3.js/issues/4629

### Related EIPs
https://eips.ethereum.org/EIPS/eip-2930 
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md 

### External Libs
Follow Lib Selection checklist.

**Comment by jdevcs** [comment]
we included Eth Transaction as part of Eth package instead of dedicated Eth Tx package.
