### ISSUE TITLE
[Rewrite 4.x] ENS

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4321]
( This is Epic for 4.x Management ) 

### ENS
Have features to interact with ENS and using ENS in other modules of web3 instead of addresses.
Migrate existing ENS functions from 1.x `web3-eth-ens` to `4.x`

### Related Issues / Feature Requests / Discussion
Create `web3-eth-ens` package structure for 4.x - #4550 
Create ENS class - #4752
Migrate ens resolver and registry abi from 1.x #4551 
Migrate contract registry functions from 1.x - #4552
Migrate Resolver functions and config from 1.x  - #4553 
ENS support in all web3 packages   - #4574

Can be released after 4.x alpha release:
ENS reverse registrar functions - #4586 
ENS permanent Registrar functions - #4588 
ENS add new ABI contract functions for feature parity with ENS in 4.x  #4600
### Features

- [ ] Registry, Resolver, Owners, TTL and Record Management
- [ ] Allow to use ENS in other parts of web3 instead of addresses

https://docs.ens.domains/
https://github.com/ChainSafe/web3.js/tree/1.x/packages/web3-eth-ens

### Dependencies / Related Modules
Providers
Eth
Contract
Transaction
Utils

### Documentation
- [ ] README ( overview, example, .. )
- [ ] Documentation

### External Libs
Follow Lib Selection checklist.
