### ISSUE TITLE
[Rewrite 4.x] Web3 Utils

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4323]
### Description  
Migrate utility functions for 1.x release of `web3-utils`
 
### Related Issues / Feature Requests / Discussion

- [x] Create web3-util package structure for the 4.x - #4349 
- [x] Migrate data type conversion utils functions from 1.x - #4350
- [x] Migrate validation utils functions from 1.x - #4351
- [x] Migrate string manipulation utils functions from 1.x #4352
- [x] Migrate hashing and encoding utils functions from 1.x #4353
- [x] Migrate types related utils functions from 1.x #4354

### Acceptance Criteria 

- [ ] README is added with overview and examples 
- [ ] Required documentations are updated 
- [ ] Test coverage is greater than 80% 
- [ ] Verify that no function left to be migrated
- [ ] Verify there is validation in functions to check for valid hex on strings if prefixed with `0x`

### External Libs
Follow Lib Selection checklist.

**Comment by luu-alex** [comment]
## Changes
### Changes in the `hash.ts`: soliditySha3, soliditySha3Raw, encodePacked:
We don't try to guess the type from the value given anymore (types must be specified)
Validate types of the values and throw errors if they don't match
address size does not default to the size of 32/40 bytes
removed ufixedfixed type support, not fully supported by solidity (https://docs.soliditylang.org/en/latest/types.html#fixed-point-numbers)
types supported: string, bool/boolean, address, uint, int, int[], bytes
### Changes in `_flattentypes` and `_jsonInterfaceMethodToString` functions
_flattentypes -> flattenTypes
_jsonInterfaceMethodToString -> jsonInterfaceMethodToString
