### ISSUE TITLE
[Rewrite 4.x] Consensus ( Beacon chain )

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4324]
( This is Epic for 4.x Management ) 

### Beacon Chain
Beacon chain API wrappers.

### Features / Discussions / Related issues 
- [ ] create package structure #4466
- [ ] create eth2 types #4467
- [ ] create eth2 api functions #4468

### 
Providers

### Documentation
- [ ] README ( overview,  example, .. )
- [ ] Documentation

### Related Issues / Feature Requests / Discussion
https://github.com/ChainSafe/web3.js/issues/4264
https://github.com/ChainSafe/web3.js/issues/4268

### External Libs
Follow Lib Selection checklist.

**Comment by jgresham** [comment]
I'd be willing to take this up. Curious if anyone is working on it or has any input.

**Comment by jdevcs** [comment]
> I'd be willing to take this up. Curious if anyone is working on it or has any input.

Thanks @jgresham  your contributions are welcome .  We will keep you in loop for discussions of this Epic, before jumping into implementation of `web3.consensus` (Beacon Chain) package , we need to look following items:

- web3 consensus provider support ( currently for (ETH 1) execution layer interaction, we have EIP1193 compatible provider [method](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-common/src/web3_base_provider.ts#L55), and for interaction with consensus layer we need provider supporting restful calls )

- allowing injected provider for consensus layer

- we need to revisit or implement following new & decoupled from eth1  :
[web3 config](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-core/src/web3_config.ts) ( if we need to maintain any state, for beacon chain  ), 
[web3 context](https://github.com/ChainSafe/web3.js/blob/4.x/packages/web3-core/src/web3_context.ts) for `web3.consensus` 
[requestManager](https://github.com/ChainSafe/web3.js/blob/c919c9b3def40fa36ca9ca9880bfc0502996a1b1/packages/web3-core/src/web3_request_manager.ts#L34) 

- Feature that we might allow user: ( allowing execution layer + consensus layer injected providers simultaneously via main web3 constructor , or providers URLs  simultaneously via main web3 constructor  )

**Comment by jgresham** [comment]
@jdevcs thank you for the detailed info and please keep me in the loop. I will hopefully be familiarizing myself in these areas over the next few weeks. If there is anyway I can get started on something minimal and working, I'd be glad to start on it, but I'm not sure where to start from here yet.
