### ISSUE TITLE
[Rewrite 4.x] Web3 Common

### ISSUE THREAD

**Issue by philknows** [ethereum/web3.js#4340]
### Description  

Create package `web3-common` with some generic stuff common among web3 usage. 
 
### Related Issues / Feature Requests / Discussion

- [x] Create web3-common package structure for the 4.x #4357
- [x] Migrate all errors to web3-common as error constructors #4359
- [x] Migrate all formatters to web3-common #4360 
- [x] Create Web3BaseProvider interface for web3-common #4361 
- [x] Create Web3BaseWallet interface for web3-common #4362
- [ ] Integrate `iban` formatter with the `inputAddressFormatter` in web3-common #4448

### Acceptance Criteria 

- [ ] README is added with overview and examples 
- [ ] Required documentations are updated 
- [ ] Test coverage is greater than 80% 
- [ ] Verify that no function left to be migrated

### External Libs
Follow Lib Selection checklist.
