### ISSUE TITLE
[Rewrite 4.x] Web3 Eth Personal

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4615]
### Description  

Create package `web3.eth.personal` with following functionality. 
 
### Related Issues / Feature Requests / Discussion
**Following function are for interacting with wallet located in Eth node, these are not for local wallet.**

- newAccount: Creates a new account
- sign : The method used for signing
- ecRecover : Recovers the account that signed the data.
- signTransaction: Signs a transaction. This account needs to be unlocked.
- sendTransaction: This method sends a transaction over the management API.
- unlockAccount: Signs data using a specific account.
- lockAccount: locksthe given account.
- getAccounts: Returns a list of accounts the node controls by using the provider and calling the RPC method `personal_listAccounts`
- importRawKey: Imports the given private key into the key store, encrypting it with the passphrase.

Along with these functions, this package must also expose following functionality by using existing packages.

- setProvider: Will change the provider for its module.
- providers: Contains the current available providers.
- givenProvider: When using web3.js in an Ethereum compatible browser, it will set with the current native provider by that browser. Will return the given provider by the (browser) environment, otherwise null.
- currentProvider: Will return the current provider, otherwise null.
- BatchRequest: Class to create and execute batch requests.
- extend: Allows extending the web3 modules. ( this function needs to be discussed for including in 4.x) 

### Acceptance Criteria 

- [ ] README is added with overview and examples 
- [ ] documentation of web3.eth.personal
- [ ] Test coverage is greater than 80% 
- [ ] Verify that no function left to be migrated

### External Libs
Follow Lib Selection checklist.

**Comment by mconnelly8** [comment]
This is being moved to an Epic record.

**Comment by jdevcs** [comment]
closed for: https://github.com/ChainSafe/web3.js/issues/4697
