### ISSUE TITLE
[Rewrite 4.x] IPC Provider

### ISSUE THREAD

**Issue by nazarhussain** [ethereum/web3.js#4642]
( This is Epic for 4.x Management ) 

### IPC Provider
IPC Provider is used to send RPC calls over Unix Socket

### Related Issues / Feature Requests / Discussion

- [x] #4643 
- [x] #4644
- [x] #4645 
- [x] #4646 
- [x] #4647 

### Dependencies / Related Modules

- [x]  #4340 Core Provider

### Documentation
- [x] README ( overview, one code snippet example, .. )
- [x] IPC Provider documentation ( Integrated with BaseProvider, have an example snippet )
 

### Related Issues
Test and add support of retry and auto reconnect features in IPC provider 
- [ ]  https://github.com/ChainSafe/web3.js/issues/4656

**Comment by jdevcs** [comment]
For future if Epic is already there kindly use same Epic and update its description. @nazarhussain @mconnelly8 
This saves time in zenhub as well.

**Comment by nazarhussain** [comment]
@jdevcs Definitely, but creating such empty epics way earlier endup not knowing which of issues are already created and are in backlog. So for better time saving, we must create and plan the foreseeable future.
