### ISSUE TITLE
[Rewrite 4.x] Web3 Eth Personal

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#4697]
### Description  

Create package `web3.eth.personal` with following functionality. 
 
### Related Issues / Feature Requests / Discussion

- [ ] [Web3 Eth Personal](https://github.com/ChainSafe/web3.js/issues/4720)

### Acceptance Criteria 

- [ ] README is added with overview and examples 
- [ ] documentation of web3.eth.personal
- [ ] Test coverage is greater than 80% 
- [ ] Verify that no function left to be migrated

### External Libs
Follow Lib Selection checklist.
