### ISSUE TITLE
Tests 4.x Alpha

### ISSUE THREAD

**Issue by mconnelly8** [ethereum/web3.js#4711]
( This is Epic for 4.x Management )

### Description  

This Epic have requirements for **4.x alpha tests**. 

- Node.js tests (**v14, v16,** v18 ) https://nodejs.org/en/about/releases/ 

- Min 2 browsers
    **Firefox**, Chromium-based browsers, Google Chrome, **Brave**, Safari, Microsoft Edge
    min versions TBD ( Firefox 60, Google Chrome 64, Safari 12, Edge 44, Brave )

- eth client/NW tests  
    Tests on min 1 Local instant seal engine ( **Geth**, Nethermind, Hyperledger Besu, Open-Eth < TBD)
    Tests on dev’s Eth clients ( **Ganache** ) 
    Tests on  at least 1 testnet ( Goerli, Rinkeby, Kovan, Ropsten ) via Infura
    Read calls on mainnet < TBD

- external Apps/APIs using web3.js: TBD ( **truffle**, openzeppelin < TBD )
- Injected Providers ( **metamask** )

 
### Related Issues / Feature Requests / Discussion
- [ ] System tests
- [ ] Unit tests: All 4.x alpha packages have >=80% coverage

### Dependencies / Related Modules
- [ ] [Web3 Eth](https://github.com/ChainSafe/web3.js/issues/4317 )
- [ ] [Web3 Contracts](https://github.com/ChainSafe/web3.js/issues/4318)
- [ ] [Web3 HTTP](https://github.com/ChainSafe/web3.js/issues/4312)
and dependencies of these packages

**Comment by jdevcs** [comment]
Edit: Added all tests requirements and **highlighted** min test requirements for 4.x Alpha:
Node: v14, v16
Browsers: Firefox, Brave
Eth Clients: Geth, Ganache
external Apps/APIs using web3.js:  truffle 
Injected Providers metamask
