### ISSUE TITLE
ENS Public Resolver Features

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#4795]
( This is Epic for 4.x Management ) 

### ENS Public Resolver
Add support of following Public Resolver features in `web3-eth-ens` package in ( web3.js 4.2.0 TBD ) https://github.com/ensdomains/resolvers/tree/master/contracts/profiles

### Features 

- [ ] Reverse Name resolution ( set ENS node name , get associated ENS node ) EIP-181

<br />  

- Check status of following and if finalized, add support:
- [ ] EIP 2304 - Multicoin support (addr()).
- [ ] EIP 634 - Text records (text()).
- [ ] EIP 205 - ABI support (ABI()).
- [ ] DNS Resolver (get and set DNS Records, check if node has records, clear DNS zone info, set and get Zone hash, )

### Documentation
- [ ] Documentation updates

### External Libs
Follow Lib Selection checklist.
