### ISSUE TITLE
Epic: Upgrade web3.js at Truffle dependencies to 4.x

### ISSUE THREAD

**Issue by Muhammad-Altabba** [ethereum/web3.js#6390]
- [x] https://github.com/web3/web3.js/issues/6144
- [x] https://github.com/web3/web3.js/issues/6389
- [x] https://github.com/web3/web3.js/issues/6391
- [x] https://github.com/web3/web3.js/issues/6442
- [ ] ... Add more here...

**Comment by Muhammad-Altabba** [comment]
Will keep track of the items in https://github.com/web3/web3.js/issues/4189
