### ISSUE TITLE
Account Abstraction 

### ISSUE THREAD

**Issue by jdevcs** [ethereum/web3.js#7347]
## AA v0.6
- [x] - AA functions
- [x] - AA current tests
- [x] - Use another package level provider for Interaction with bundler
- [x] - AA package config for publishing 
- [ ] - Export from main web3 
- [ ] - param validation and result formatting 
- [x] - Integration in existing Package and API documentation
- [ ] - Additional util functions
  - get nonce, 
  - get InitCode for simple account creation using sample AccountFactory or optional provided ABI,
  - `pm_sponsorUserOperation` paymaster functions
  - signing
- [Account Abstraction guide / tutorial](https://github.com/web3/web3.js/issues/7335)
  - What is AA, different components of AA(userOp, bundlers, paymasters, entrypoint, contract account), Its usages/scenarios ( different kinds of paymasters, accounts factory, etc )
  - Web3.js AA package functions
  - Infrastructure ( existing providers, vs Local infrastructure using docker compose and stackup )
  - Create sample account in first UserOp using factory contract
  - Sponsored UserOP with Paymaster
  - Send value transfer UserOP
  - Send ERC20 transfer UserOP
  - Write code snippets in stackblitz for above demonstrations
- [Integration and E2E testing](https://github.com/web3/web3.js/issues/7336)
     - use dev net https://github.com/stackup-wallet/erc-4337-devnet in web3.js CI or local Infrastructure
- [Push coverage and integrate Codecov](https://github.com/web3/web3.js/issues/7337)
## AA v0.7
- differences [v0.6 and v0.7](https://github.com/eth-infinitism/account-abstraction/releases)
- update AA Useroperation structures and add support of v0.7 functions
- Add tests ( Unit / Integration )
- Add v0.7 functions documentation 
- Add v0.7 Guides

**Comment by tomteman** [comment]
Hey, I'm from the Ethereum Foundation's Account Abstraction team, I'd be happy to offer assistance to help complete this Epic, please feel free to DM me
